name: gpi_ling_new
nof_iterations: 10000
learning_rate: 0.0001
learning_rate_steps: 1000
learning_rate_decay: 0.5
load_model_name: "gpi_ling_new_best_module.ckpt"
use_saved_model: False
batch_size: 20
predicate_pos_neg_ratio: 10
lr_object_coeff: 4
layers: [500, 500, 500]
gpu: 0

